Repository netdevopsbr/netbox-proxbox, pull requests merged in 2022-05, with the labels that each got.

#44 Closes #36 and #42 - Add support to Netbox >v3.2
  README.md
  netbox_proxbox/navigation.py
  netbox_proxbox/tables.py
  netbox_proxbox/templates/netbox_proxbox/home.html
  netbox_proxbox/urls.py
  netbox_proxbox/views.py
  settings.py
Labels: feature

#57 remove numpy and matplotlib - they do not seem to be in use
  pyproject.toml
  setup.py
Labels: accepted

#56 document when username and password are required
  README.md
Labels: documentation, accepted

#55 Closes #37 - Automatically publish the package on PyPI
  .github/workflows/pypi.yml
  README.md
  pyproject.toml
  setup.py
Labels: feature, under review
