Repository netdevopsbr/netbox-proxbox, pull requests merged in 2023-07, with the labels that each got.

#122 Add multi-cluster support
  README.md
  netbox_custom_fields.csv
  netbox_proxbox/__init__.py
  netbox_proxbox/proxbox_api/create/dcim.py
  netbox_proxbox/proxbox_api/create/virtualization.py
  netbox_proxbox/proxbox_api/plugins_config.py
  netbox_proxbox/proxbox_api/remove.py
  netbox_proxbox/proxbox_api/update.py
  netbox_proxbox/proxbox_api/updates/node.py
  netbox_proxbox/proxbox_api/updates/virtual_machine.py
  netbox_proxbox/templates/netbox_proxbox/home.html
  netbox_proxbox/templates/netbox_proxbox/proxmox_vm_full_update.html
  netbox_proxbox/urls.py
  netbox_proxbox/views.py
  reinstall.sh
Labels: feature, under review

#126 Closes #33 and #123 - Add multi cluster support
  README.md
  netbox_custom_fields.csv
  netbox_proxbox/__init__.py
  netbox_proxbox/proxbox_api/create/dcim.py
  netbox_proxbox/proxbox_api/create/virtualization.py
  netbox_proxbox/proxbox_api/plugins_config.py
  netbox_proxbox/proxbox_api/remove.py
  netbox_proxbox/proxbox_api/update.py
  netbox_proxbox/proxbox_api/updates/node.py
  netbox_proxbox/proxbox_api/updates/virtual_machine.py
  netbox_proxbox/templates/netbox_proxbox/home.html
  netbox_proxbox/templates/netbox_proxbox/proxmox_vm_full_update.html
  netbox_proxbox/urls.py
  netbox_proxbox/views.py
  reinstall.sh
Labels: feature

#133 Fixed README missing code snippet markdown formatting
  README.md
Labels: documentation, accepted

#134 Closes #89 - Implement API communication with Proxmox using FastAPI
  FASTAPI.md
  netbox_proxbox/api/main.py
  netbox_proxbox/fastapi/main.py
  netbox_proxbox/proxbox_api/main.py
  setup.py
Labels: feature

#135 Revert proxbox_api/__init__.py change from #07799d2
  netbox_proxbox/proxbox_api/__init__.py
Labels: bug, accepted
