Repository netdevopsbr/netbox-proxbox, pull requests merged in 2023-03, with the labels that each got.

#84 Get Network information from Proxmox
  netbox_proxbox/proxbox_api/update.py
  netbox_proxbox/proxbox_api/updates/node.py
  netbox_proxbox/proxbox_api/updates/virtual_machine.py
Labels: under review

#83 adding missing use of PROXMOX_PORT
  netbox_proxbox/proxbox_api/plugins_config.py
Labels: under review

#95 Close #94 - Fix duplicate update due to case sensitive mismatch
  netbox_proxbox/proxbox_api/updates/virtual_machine.py
Labels: accepted

#100 Closes #27 and #75 - Create duplicate object with (2) appended if it already exist on Netbox.
  netbox_proxbox/proxbox_api/create/dcim.py
  netbox_proxbox/proxbox_api/create/extras.py
  netbox_proxbox/proxbox_api/create/virtualization.py
  netbox_proxbox/proxbox_api/remove.py
  netbox_proxbox/proxbox_api/update.py
  netbox_proxbox/proxbox_api/updates/node.py
  netbox_proxbox/templates/netbox_proxbox/home.html
  netbox_proxbox/templates/netbox_proxbox/proxmox_vm_full_update.html
  netbox_proxbox/views.py
Labels: bug, accepted

#99 Close #98 - Correcting missing MTU and wrong identifier
  README.md
  netbox_proxbox/proxbox_api/updates/node.py
Labels: bug, accepted

#102 Close #96 - Start using 'logging' library
  README.md
  netbox_proxbox/proxbox_api/create/dcim.py
  netbox_proxbox/proxbox_api/create/virtualization.py
  netbox_proxbox/proxbox_api/remove.py
  netbox_proxbox/proxbox_api/update.py
  netbox_proxbox/proxbox_api/updates/node.py
  netbox_proxbox/proxbox_api/updates/virtual_machine.py
Labels: feature, accepted

#103 Fixed the mgmt_only and proxmox_keep_interface bool logic
  netbox_proxbox/proxbox_api/updates/node.py
Labels: under review
